# CONSUMO DI SUOLO: STRUMENTI PER UN DIALOGO
## Salvadori  (ISAFOM CNR )

### 

### Abstract


Parlare del consumo di suolo è parlare di un fenomeno che ha accompagnato per secoli la storia dell’umanità. Del resto, al di là di qualche mente illuminata in epoche precedenti, solo tra la fine del secolo scorso e quello attuale l’umanità ha preso coscienza dei propri doveri nei confronti dell’ambiente e della sostenibilità. Nelle epoche passate umanizzare lo spazio significava reificarlo: dargli una forma artificiale,  sfruttarne le risorse, organizzarlo in vaste colture. La "territorializzazione" era anzitutto associata alla costruzione di edifici: strutture e grandi città. I secoli passati, fino a ieri, vedevano nella città grande, popolosissima, ordinata e razionalizzata in base ad una narrazione ideale del progresso, un fondamentale obiettivo e destino dell’umanità. Era un’idea di proiezione verso il futuro sviluppata intorno all’ideale tecnologico, nella convinzione che appunto la tecnologia, il libero mercato, una globalizzazione di produzioni e traffici che non è cosa di oggi, ma risale a molto tempo fa, potessero risolvere i problemi materiali dell’umanità, strappandola a schiavitù millenarie. Era il sogno di regolare definitivamente i rapporti fra le persone e lo spazio naturale secondo una volontà e una progettualità dettate dal "progresso".
Dato che siamo nel contesto di una grande esposizione universale, viene a mente quel famoso monumento di un’altra esposizione universale, un’opera costruita e un esito anch’essa, in fin dei conti, del consumo di suolo: la Torre Eiffel a Parigi. Quell’esposizione universale era un canto rivolto al progresso di una umanità che per la prima volta dopo secoli, nel pieno della Belle Epoque, sentiva di poter asservire completamente il pianeta alla propria superiorità scientifica e tecnica: una superiorità fondamentale, radicale, ontologica. Attraverso quella superiorità l’Uomo intendeva superare i limiti tradizionali della propria azione e della propria esistenza: la trappola malthusiana, le malattie, le diseguaglianze. Sperava di assoggettare il pianeta con i suoi spazi, per trasformarli, civilizzarli, umanizzarli. E la Torre Eiffel simboleggiava tutto questo, cioè l’eredità spirituale che l’Ottocento voleva lasciare al Novecento. Un’eredità di forza, di slancio verso un secolo che sarebbe dovuto essere radioso e luminoso come non lo era stata alcuna epoca precedente, anche in virtù del definitivo dominio dell’umanità sulla natura. Oggi, più di cent’anni dopo, riflettiamo sulla portata di quell’esperienza e sui suoi limiti fondamentali di visione. Oggi abbiamo capito che se l’umanità potrà continuare a esistere sul nostro grande e generoso, ma fragile pianeta, ciò sarà solo in virtù dell’aver rispettato la sua intrinseca delicatezza; di aver cioè compreso profondamente e raggiunto quella sostenibilità e quell’uguaglianza rispettosa nell’accesso alle risorse che restano presupposti fondamentali di speranza per l'avvenire, a prescindere dalla potenza tecnologica di oggi (assai più grande di quella che avevamo nell’Ottocento).
Il consumo di suolo e le norme che puntano a limitarlo sono appunto i due aspetti, per così dire, di “unità fondamentale” di questa relazione nuova, diversa, fra l’umanità e il pianeta. Unità fondamentale perché espressa a livello puntuale, locale, in un qui molto concreto che è quello della nostra città, della nostra regione, del nostro paese. Consumare il suolo è togliere materia e forza vitale allo spazio che viviamo; materia per la vita nostra e delle future generazioni. Parliamo infatti di Consumo di suolo qui in Italia e di normative per limitarlo qui in Italia; parliamo certamente anche di consumo di suolo e normative per limitarlo in Europa e nel mondo intero. Ma qui oggi è di casa nostra che dobbiamo parlare.
La normativa si pone il problema di intervenire sul consumo di suolo; aprendo ovviamente una questione che è rilevante e problematica, per i diversi meccanismi che implica e per la complessità delle relazioni che richiede di considerare in modo bilanciato.  O’Riordan e Turner avevano decenni fa classificato gli approcci possibili nel progettare visioni e politiche ambientali secondo le famose due categorie di “ecocentrismo” e “tecnocentrismo”, a seconda che l’obiettivo profondo fosse la difesa dell’ambiente o dell’iniziativa umana. Per buona che fosse l’idea, con le sue molteplici interpretazioni successive, in un contesto eminentemente pratico come quello di oggi bisogna andare oltre. Andare oltre significa capire che il legislatore ha per interlocutori attori e stakeholder rappresentanti le diverse componenti di questa complessità. Legiferare oggi sul consumo di suolo significa doversi confrontare con un complesso quadro normativo generale che del problema non teneva conto; e rapportarsi con un territorio che ha avuto una storia estremamente complessa, lungamente stratificato attraverso le epoche. Un territorio, quello italiano di oggi, che significativamente conserva ancora pienamente attivi alcuni suoi caratteri storici anche relativi al consumo di suolo.
L’Italia che è emersa dal processo di unificazione dell’Ottocento, fino ad oggi, ha assistito allo sviluppo di potenti fenomeni di territorializzazione – legati all’industrializzazione, ma non solo. Basta guardare come si è strutturato e aggregato fino ad oggi il territorio della Pianura Padana e di quello che fu il Lombardo-Veneto. Basta osservare come si è evoluto quel caso unico di territorializzazione che è l’area metropolitana di Roma, a partire da una città che da capitale pontificia contava poco più di 200.000 abitanti, i quali non arrivavano a riempire neanche i 19 km di perimetro delle Mura Aureliane; parliamo ancora di un’area di particolare importanza e criticità, come quella intorno al Vesuvio, tale da creare un sistema metropolitano fra i più vasti e complessi d’Europa, concentrato in un contesto ambientale che richiede non solo salvaguardia, ma anche attenzione ai fini della protezione e della tutela dei cittadini. Bastano appena questi esempi a costituire uno scenario di riflessione fondamentale da cui si dovrebbe partire nella discussione proposta in questa sede, sui disegni di una nuova normativa.
